apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: dex
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: quay.io/dexidp/dex:v2.21.0
          command:
            - /usr/local/bin/dex
            - serve
            - /etc/dex/cfg/config.yaml
          ports:
            - containerPort: 30443
              name: https
          volumeMounts:
            - name: config
              mountPath: /etc/dex/cfg
            - name: tls
              mountPath: /etc/dex/tls
      volumes:
        - name: config
          configMap:
            name: server
            items:
              - key: config.yaml
                path: config.yaml
        - name: tls
          secret:
            secretName: dex.tls
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: dex
  labels:
    app: server
spec:
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      nodePort: 30443
      port: 30443
      targetPort: https
  selector:
    app: server
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: server
  namespace: dex
data:
  config.yaml: |
    issuer: https://kubelogin-acceptance-test-control-plane:30443/dex
    web:
      https: 0.0.0.0:30443
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    storage:
      type: sqlite3
      config:
        file: /tmp/dex.db
    staticClients:
      - id: YOUR_CLIENT_ID
        redirectURIs:
          - http://localhost:8000
        name: kubelogin
        secret: YOUR_CLIENT_SECRET
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    # required for staticPasswords
    enablePasswordDB: true
