apiVersion: v1
kind: Config
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://kubelogin-acceptance-test-control-plane:30443/dex
      - --oidc-client-id=YOUR_CLIENT_ID
      - --oidc-client-secret=YOUR_CLIENT_SECRET
      - --oidc-extra-scope=email
      - --certificate-authority=output/ca.crt
      - --token-cache-dir=output/token-cache
      - --listen-address=127.0.0.1:8000
      - --skip-open-browser
      - -v1
      command: kubectl
contexts:
- context:
    cluster: kind-kubelogin-acceptance-test
    user: oidc
  name: oidc
current-context: oidc
