// Code generated by mockery v2.13.1. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// mockTestingLogger is an autogenerated mock type for the testingLogger type
type mockTestingLogger struct {
	mock.Mock
}

type mockTestingLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTestingLogger) EXPECT() *mockTestingLogger_Expecter {
	return &mockTestingLogger_Expecter{mock: &_m.Mock}
}

// Logf provides a mock function with given fields: format, v
func (_m *mockTestingLogger) Logf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// mockTestingLogger_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type mockTestingLogger_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//  - format string
//  - v ...interface{}
func (_e *mockTestingLogger_Expecter) Logf(format interface{}, v ...interface{}) *mockTestingLogger_Logf_Call {
	return &mockTestingLogger_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{format}, v...)...)}
}

func (_c *mockTestingLogger_Logf_Call) Run(run func(format string, v ...interface{})) *mockTestingLogger_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockTestingLogger_Logf_Call) Return() *mockTestingLogger_Logf_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTnewMockTestingLogger interface {
	mock.TestingT
	Cleanup(func())
}

// newMockTestingLogger creates a new instance of mockTestingLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockTestingLogger(t mockConstructorTestingTnewMockTestingLogger) *mockTestingLogger {
	mock := &mockTestingLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
