// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stdio_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStdout creates a new instance of MockStdout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStdout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStdout {
	mock := &MockStdout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStdout is an autogenerated mock type for the Stdout type
type MockStdout struct {
	mock.Mock
}

type MockStdout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStdout) EXPECT() *MockStdout_Expecter {
	return &MockStdout_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockStdout
func (_mock *MockStdout) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStdout_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockStdout_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockStdout_Expecter) Write(p interface{}) *MockStdout_Write_Call {
	return &MockStdout_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockStdout_Write_Call) Run(run func(p []byte)) *MockStdout_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStdout_Write_Call) Return(n int, err error) *MockStdout_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStdout_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStdout_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStdin creates a new instance of MockStdin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStdin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStdin {
	mock := &MockStdin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStdin is an autogenerated mock type for the Stdin type
type MockStdin struct {
	mock.Mock
}

type MockStdin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStdin) EXPECT() *MockStdin_Expecter {
	return &MockStdin_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockStdin
func (_mock *MockStdin) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStdin_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockStdin_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *MockStdin_Expecter) Read(p interface{}) *MockStdin_Read_Call {
	return &MockStdin_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *MockStdin_Read_Call) Run(run func(p []byte)) *MockStdin_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStdin_Read_Call) Return(n int, err error) *MockStdin_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStdin_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStdin_Read_Call {
	_c.Call.Return(run)
	return _c
}
