dir: mocks/{{.SrcPackagePath}}_mock
pkgname: '{{.SrcPackageName}}_mock'
filename: mocks.go
template: testify
packages:
  github.com/int128/kubelogin:
    config:
      all: true
      recursive: true
  io:
    interfaces:
      Closer: {}
