apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oidc-login
spec:
  homepage: https://github.com/int128/kubelogin
  shortDescription: Log in to the OpenID Connect provider
  description: |
    This is a kubectl plugin for Kubernetes OpenID Connect (OIDC) authentication.

    ## Credential plugin mode
    kubectl executes oidc-login before calling the Kubernetes APIs.
    oidc-login automatically opens the browser and you can log in to the provider.
    After authentication, kubectl gets the token from oidc-login and you can access the cluster.
    See https://github.com/int128/kubelogin#credential-plugin-mode for more.

    ## Standalone mode
    Run `kubectl oidc-login`.
    It automatically opens the browser and you can log in to the provider.
    After authentication, it writes the token to the kubeconfig and you can access the cluster.
    See https://github.com/int128/kubelogin#standalone-mode for more.

  caveats: |
    You need to setup the OIDC provider, Kubernetes API server, role binding and kubeconfig.
    See https://github.com/int128/kubelogin for more.

  version: {{ env "VERSION" }}
  platforms:
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_linux_amd64.zip
      sha256: "{{ sha256 .linux_amd64_archive }}"
      bin: kubelogin
      files:
        - from: kubelogin
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_darwin_amd64.zip
      sha256: "{{ sha256 .darwin_amd64_archive }}"
      bin: kubelogin
      files:
        - from: kubelogin
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - uri: https://github.com/int128/kubelogin/releases/download/{{ env "VERSION" }}/kubelogin_windows_amd64.zip
      sha256: "{{ sha256 .windows_amd64_archive }}"
      bin: kubelogin.exe
      files:
        - from: kubelogin.exe
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: windows
          arch: amd64
