package keys

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"io"
	"io/ioutil"
	"os"
	"strings"
)

// Keys represents a pair of certificate and key.
type Keys struct {
	CertPath     string
	KeyPath      string
	CACertPath   string
	CACertBase64 string
	TLSConfig    *tls.Config
}

// None represents non-TLS.
var None Keys

// Server is a Keys for TLS server.
// These files should be generated by Makefile before test.
var Server = Keys{
	CertPath:     "keys/testdata/server.crt",
	KeyPath:      "keys/testdata/server.key",
	CACertPath:   "keys/testdata/ca.crt",
	CACertBase64: readAsBase64("keys/testdata/ca.crt"),
	TLSConfig:    newTLSConfig("keys/testdata/ca.crt"),
}

func readAsBase64(name string) string {
	f, err := os.Open(name)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	var s strings.Builder
	e := base64.NewEncoder(base64.StdEncoding, &s)
	if _, err := io.Copy(e, f); err != nil {
		panic(err)
	}
	if err := e.Close(); err != nil {
		panic(err)
	}
	return s.String()
}

func newTLSConfig(name string) *tls.Config {
	b, err := ioutil.ReadFile(name)
	if err != nil {
		panic(err)
	}
	p := x509.NewCertPool()
	if !p.AppendCertsFromPEM(b) {
		panic("could not append the CA cert")
	}
	return &tls.Config{RootCAs: p}
}
