// Code generated by mockery v2.53.3. DO NOT EDIT.

package client_mock

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockhttpTransportFn is an autogenerated mock type for the httpTransportFn type
type MockhttpTransportFn struct {
	mock.Mock
}

type MockhttpTransportFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockhttpTransportFn) EXPECT() *MockhttpTransportFn_Expecter {
	return &MockhttpTransportFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: req
func (_m *MockhttpTransportFn) Execute(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockhttpTransportFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockhttpTransportFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockhttpTransportFn_Expecter) Execute(req interface{}) *MockhttpTransportFn_Execute_Call {
	return &MockhttpTransportFn_Execute_Call{Call: _e.mock.On("Execute", req)}
}

func (_c *MockhttpTransportFn_Execute_Call) Run(run func(req *http.Request)) *MockhttpTransportFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockhttpTransportFn_Execute_Call) Return(_a0 *http.Response, _a1 error) *MockhttpTransportFn_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockhttpTransportFn_Execute_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *MockhttpTransportFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhttpTransportFn creates a new instance of MockhttpTransportFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhttpTransportFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockhttpTransportFn {
	mock := &MockhttpTransportFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
