// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/int128/kubelogin/pkg/adaptors/browser"
	"github.com/int128/kubelogin/pkg/adaptors/certpool"
	"github.com/int128/kubelogin/pkg/adaptors/cmd"
	"github.com/int128/kubelogin/pkg/adaptors/credentialplugin"
	"github.com/int128/kubelogin/pkg/adaptors/env"
	"github.com/int128/kubelogin/pkg/adaptors/jwtdecoder"
	"github.com/int128/kubelogin/pkg/adaptors/kubeconfig"
	"github.com/int128/kubelogin/pkg/adaptors/logger"
	"github.com/int128/kubelogin/pkg/adaptors/oidcclient"
	"github.com/int128/kubelogin/pkg/adaptors/tokencache"
	"github.com/int128/kubelogin/pkg/usecases/authentication"
	credentialplugin2 "github.com/int128/kubelogin/pkg/usecases/credentialplugin"
	"github.com/int128/kubelogin/pkg/usecases/setup"
	"github.com/int128/kubelogin/pkg/usecases/standalone"
)

// Injectors from di.go:

func NewCmd() cmd.Interface {
	loggerInterface := logger.New()
	browserBrowser := &browser.Browser{}
	interaction := &credentialplugin.Interaction{}
	cmdInterface := NewCmdForHeadless(loggerInterface, browserBrowser, interaction)
	return cmdInterface
}

func NewCmdForHeadless(loggerInterface logger.Interface, browserInterface browser.Interface, credentialpluginInterface credentialplugin.Interface) cmd.Interface {
	newFunc := _wireNewFuncValue
	decoder := &jwtdecoder.Decoder{}
	envEnv := &env.Env{}
	authCode := &authentication.AuthCode{
		Env:     envEnv,
		Browser: browserInterface,
		Logger:  loggerInterface,
	}
	authCodeKeyboard := &authentication.AuthCodeKeyboard{
		Env:    envEnv,
		Logger: loggerInterface,
	}
	ropc := &authentication.ROPC{
		Env:    envEnv,
		Logger: loggerInterface,
	}
	authenticationAuthentication := &authentication.Authentication{
		NewOIDCClient:    newFunc,
		JWTDecoder:       decoder,
		Logger:           loggerInterface,
		Env:              envEnv,
		AuthCode:         authCode,
		AuthCodeKeyboard: authCodeKeyboard,
		ROPC:             ropc,
	}
	kubeconfigKubeconfig := &kubeconfig.Kubeconfig{
		Logger: loggerInterface,
	}
	certpoolNewFunc := _wireCertpoolNewFuncValue
	standaloneStandalone := &standalone.Standalone{
		Authentication: authenticationAuthentication,
		Kubeconfig:     kubeconfigKubeconfig,
		NewCertPool:    certpoolNewFunc,
		Logger:         loggerInterface,
	}
	root := &cmd.Root{
		Standalone: standaloneStandalone,
		Logger:     loggerInterface,
	}
	repository := &tokencache.Repository{}
	getToken := &credentialplugin2.GetToken{
		Authentication:       authenticationAuthentication,
		TokenCacheRepository: repository,
		NewCertPool:          certpoolNewFunc,
		Interaction:          credentialpluginInterface,
		Logger:               loggerInterface,
	}
	cmdGetToken := &cmd.GetToken{
		GetToken: getToken,
		Logger:   loggerInterface,
	}
	setupSetup := &setup.Setup{
		Authentication: authenticationAuthentication,
		NewCertPool:    certpoolNewFunc,
		Logger:         loggerInterface,
	}
	cmdSetup := &cmd.Setup{
		Setup: setupSetup,
	}
	cmdCmd := &cmd.Cmd{
		Root:     root,
		GetToken: cmdGetToken,
		Setup:    cmdSetup,
		Logger:   loggerInterface,
	}
	return cmdCmd
}

var (
	_wireNewFuncValue         = oidcclient.NewFunc(oidcclient.New)
	_wireCertpoolNewFuncValue = certpool.NewFunc(certpool.New)
)
