// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package loader_mock

import (
	"crypto/tls"

	"github.com/int128/kubelogin/pkg/tlsclientconfig"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockInterface
func (_mock *MockInterface) Load(config tlsclientconfig.Config) (*tls.Config, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *tls.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(tlsclientconfig.Config) (*tls.Config, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(tlsclientconfig.Config) *tls.Config); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(tlsclientconfig.Config) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockInterface_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - config tlsclientconfig.Config
func (_e *MockInterface_Expecter) Load(config interface{}) *MockInterface_Load_Call {
	return &MockInterface_Load_Call{Call: _e.mock.On("Load", config)}
}

func (_c *MockInterface_Load_Call) Run(run func(config tlsclientconfig.Config)) *MockInterface_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tlsclientconfig.Config
		if args[0] != nil {
			arg0 = args[0].(tlsclientconfig.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterface_Load_Call) Return(config1 *tls.Config, err error) *MockInterface_Load_Call {
	_c.Call.Return(config1, err)
	return _c
}

func (_c *MockInterface_Load_Call) RunAndReturn(run func(config tlsclientconfig.Config) (*tls.Config, error)) *MockInterface_Load_Call {
	_c.Call.Return(run)
	return _c
}
