// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/google/wire"
	adaptors2 "github.com/int128/kubelogin/adaptors"
	"github.com/int128/kubelogin/adaptors/interfaces"
	"github.com/int128/kubelogin/usecases"
	"github.com/int128/kubelogin/usecases/login"
)

// Injectors from di.go:

func NewCmd(logger adaptors.Logger) adaptors.Cmd {
	kubeConfig := &adaptors2.KubeConfig{}
	http := &adaptors2.HTTP{
		Logger: logger,
	}
	oidc := &adaptors2.OIDC{}
	loginLogin := &login.Login{
		KubeConfig: kubeConfig,
		HTTP:       http,
		OIDC:       oidc,
		Logger:     logger,
	}
	cmd := &adaptors2.Cmd{
		Login:  loginLogin,
		Logger: logger,
	}
	return cmd
}

// di.go:

var usecasesSet = wire.NewSet(login.Login{}, wire.Bind((*usecases.Login)(nil), (*login.Login)(nil)))
