// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/int128/kubelogin/adaptors"
	"github.com/int128/kubelogin/adaptors/cmd"
	"github.com/int128/kubelogin/adaptors/env"
	"github.com/int128/kubelogin/adaptors/kubeconfig"
	"github.com/int128/kubelogin/adaptors/logger"
	"github.com/int128/kubelogin/adaptors/oidc"
	"github.com/int128/kubelogin/usecases"
	"github.com/int128/kubelogin/usecases/auth"
	"github.com/int128/kubelogin/usecases/login"
)

// Injectors from di.go:

func NewCmd() adaptors.Cmd {
	adaptorsLogger := logger.New()
	factory := &oidc.Factory{
		Logger: adaptorsLogger,
	}
	envEnv := &env.Env{}
	showLocalServerURL := &auth.ShowLocalServerURL{
		Logger: adaptorsLogger,
	}
	authentication := &auth.Authentication{
		OIDC:               factory,
		Env:                envEnv,
		Logger:             adaptorsLogger,
		ShowLocalServerURL: showLocalServerURL,
	}
	kubeconfigKubeconfig := &kubeconfig.Kubeconfig{}
	loginLogin := &login.Login{
		Authentication: authentication,
		Kubeconfig:     kubeconfigKubeconfig,
		Logger:         adaptorsLogger,
	}
	exec := &login.Exec{
		Authentication: authentication,
		Kubeconfig:     kubeconfigKubeconfig,
		Env:            envEnv,
		Logger:         adaptorsLogger,
	}
	cmdCmd := &cmd.Cmd{
		Login:        loginLogin,
		LoginAndExec: exec,
		Logger:       adaptorsLogger,
	}
	return cmdCmd
}

func NewCmdWith(adaptorsLogger adaptors.Logger, loginShowLocalServerURL usecases.LoginShowLocalServerURL) adaptors.Cmd {
	factory := &oidc.Factory{
		Logger: adaptorsLogger,
	}
	envEnv := &env.Env{}
	authentication := &auth.Authentication{
		OIDC:               factory,
		Env:                envEnv,
		Logger:             adaptorsLogger,
		ShowLocalServerURL: loginShowLocalServerURL,
	}
	kubeconfigKubeconfig := &kubeconfig.Kubeconfig{}
	loginLogin := &login.Login{
		Authentication: authentication,
		Kubeconfig:     kubeconfigKubeconfig,
		Logger:         adaptorsLogger,
	}
	exec := &login.Exec{
		Authentication: authentication,
		Kubeconfig:     kubeconfigKubeconfig,
		Env:            envEnv,
		Logger:         adaptorsLogger,
	}
	cmdCmd := &cmd.Cmd{
		Login:        loginLogin,
		LoginAndExec: exec,
		Logger:       adaptorsLogger,
	}
	return cmdCmd
}
