name: docker

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build-metadata.outputs.image-uri }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@ff5e26ea6bb16b6534e803d629105838cb2c9f1b # v1.69.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc64le
      - uses: int128/docker-build-metadata-action@e79380bba61a31731454abcc0148708b32b0d65d # v2.7.0
        id: build-metadata
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digest: ${{ steps.build.outputs.digest }}

  test:
    if: needs.build.outputs.image-uri != ''
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: docker run --rm "$IMAGE_URI" --help
        env:
          IMAGE_URI: ${{ needs.build.outputs.image-uri }}
