name: docker

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build-metadata.outputs.image-uri }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@e7428bcd6851e35bd024e91ea18c0da8c0a098b4 # v1.60.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: build
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc64le
      - uses: int128/docker-build-metadata-action@148eee3f0a84c2ba42477f370b92dadf2d465d00 # v2.5.0
        id: build-metadata
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digest: ${{ steps.build.outputs.digest }}

  test:
    if: needs.build.outputs.image-uri != ''
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: docker run --rm "$IMAGE_URI" --help
        env:
          IMAGE_URI: ${{ needs.build.outputs.image-uri }}
