name: docker

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yaml
      - pkg/**
      - go.*
      - Dockerfile
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build-metadata.outputs.image-uri }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-build-cache-config-action@97740da6c51c4bcd68c7519e2179e6a93389b027 # v1.71.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc64le
      - uses: int128/docker-build-metadata-action@b583f8733fda08afce8b1f3d86fb27bd6ef6d714 # v2.8.0
        id: build-metadata
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          digest: ${{ steps.build.outputs.digest }}

  test:
    if: needs.build.outputs.image-uri != ''
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: docker run --rm "$IMAGE_URI" --help
        env:
          IMAGE_URI: ${{ needs.build.outputs.image-uri }}
