on:
  push:
    paths:
      - .github/workflows/golangci-lint.yaml
      - '**.go'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
